GET http://localhost:4050/api/colors HTTP/1.1

###


GET http://localhost:4050/api/colors/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiYm9iIiwicm9sZXMiOlsiYWRtaW4iLCJ1c2VyIl19LCJpYXQiOjE2Mzc1NDMyNTcsImV4cCI6MTYzNzU0MzM3N30.wBB35s1PSR7_jLIqrlEvNPBNcD8HcmsF4fiM5Yz2DhI

###

GET http://localhost:4050/api/colors/1 HTTP/1.1

###

POST http://localhost:4050/api/colors HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiYm9iIiwicm9sZXMiOlsiYWRtaW4iLCJ1c2VyIl19LCJpYXQiOjE2Mzc1NDMyNTcsImV4cCI6MTYzNzU0MzM3N30.wBB35s1PSR7_jLIqrlEvNPBNcD8HcmsF4fiM5Yz2DhI

{
  "name": "orange",
  "hexcode": "ffff00"
}

###
PUT http://localhost:4050/api/colors/4 HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiYm9iIiwicm9sZXMiOlsiYWRtaW4iLCJ1c2VyIl19LCJpYXQiOjE2Mzc1NDMyNTcsImV4cCI6MTYzNzU0MzM3N30.wBB35s1PSR7_jLIqrlEvNPBNcD8HcmsF4fiM5Yz2DhI

{
  "id": 4,
  "name": "orange",
  "hexcode": "ffffdd"
}

###

DELETE http://localhost:4050/api/colors/4 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiYm9iIiwicm9sZXMiOlsiYWRtaW4iLCJ1c2VyIl19LCJpYXQiOjE2Mzc1NDMyNTcsImV4cCI6MTYzNzU0MzM3N30.wBB35s1PSR7_jLIqrlEvNPBNcD8HcmsF4fiM5Yz2DhI
