

POST http://localhost:4050/login HTTP/1.1
Content-Type: application/json

{ "username": "bob", "profile": "admin" }

###

POST http://localhost:4050/login HTTP/1.1
Content-Type: application/json

{ "username": "bob", "profile": "user" }

###

GET http://localhost:4050/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjp7InVzZXJuYW1lIjoiYm9iIiwicm9sZXMiOlsidXNlciJdfSwiaWF0IjoxNjM3NDI4ODczLCJleHAiOjE2Mzc1MTUyNzN9.N06X7vBWmZ8EuvJ3fg_UoG7ZSYU0vzmAium3nD-XiXo